[package]
name = "AW12_Responses"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
flate2 = "1.0.26"
serde = { version = "1.0.174", features = ["derive"] }
serde_json = "1.0.103"
